### ISSUE TITLE
newlines not displayed in some text editors

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#1]
newlines are not showing up exported scales when using 1Writer (iOS) and Notepad (Win)

**Comment by suhr** [comment]
Windows uses `\r\n` instead of `\n` for newlines.

**Comment by SeanArchibald** [comment]
What I'm trying to figure out:

1) Is there a way to make this "just work" for everybody, without adding new options to the interface?
2) If instruments/synths all accept the `\n` newline anyway, does it really matter if some text editors don't display properly?

**Comment by suhr** [comment]
> Is there a way to make this "just work" for everybody, without adding new options to the interface?

I believe using `\r\n` instead of `\n` is that way. File formats support it.

> If instruments/synths all accept the `\n` newline anyway, does it really matter if some text editors don't display properly?

It might be handy, though almost any decent text editor understands `\n`.

It's rather surprising 1Writer doesn't understand it. I thought only Notepad has this issue.

**Comment by SeanArchibald** [comment]
the fix has now been merged into the master branch
