### ISSUE TITLE
Problems with .txt file for Kontakt 6

### ISSUE THREAD

**Issue by mxSilver** [SeanArchibald/scale-workshop#100]
Hello,
This may likely be user error on my part since I'm very new to Kontakt, microtonal music and scripting. 

After following the tutorials and exporting a 5EDO and 22EDO Kontakt .txt files I followed the directions from this tutorial and tried using one or the other by pasting the .txt into an empty Kontakt Script Editor.
https://soundbytesmag.net/technique-microtuning-in-kontakt-5-and-6/

For a reason beyond my ability to troubleshoot only one note (a single A) plays on my midi keyboard or on the virtual Kontakt keyboard. Here's a copy of the 5EDO
[5 equal divisions of 2_1.txt](https://github.com/SeanArchibald/scale-workshop/files/4441523/5.equal.divisions.of.2_1.txt)

I apologize for my ignorance but I'm really having trouble finding information thru web searches that enables me to figure this out by myself. Thanks so much for any assistance and/or tips!

**Comment by SeanArchibald** [comment]
I don't have a copy of Kontakt to test with, but I know that some Kontakt instruments don't work well when you try to retune them. To rule that out, have you tried getting the script to work with any other Kontakt instruments?
