### ISSUE TITLE
Problem with Scala software no sound comes from it 

### ISSUE THREAD

**Issue by Alfredokraus** [SeanArchibald/scale-workshop#102]
HI
I install the last version of Scala 2.42 on my laptop Mac with the Osx Sierra 10.12.6. I follow all steps that the web said. I Installed the X11, the symplesynth and the Scala as I said before. I put the equal 24 scale to listen to it but when I put the play window and I said that there is a midi error on the output I hit any note and no sound comes from it, also the scala said there is a failure " (scala:2657): Gtk-CRITICAL **: gtk_box_pack: assertion 'child->parent == NULL' failed "
How can I fix it in order to listen the scale with mouse?
Thanks in advance

**Comment by meszaros-lajos-gyorgy** [comment]
This github repo is for Scale Workshop, not for Scala. If you want to report a bug about scala, then you should get in contact with the author at: coul@huygens-fokker.org
