### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by JellyMonster1** [SeanArchibald/scale-workshop#111]
I can play notes for a short time then no sound.  A refresh sorts it out but its only temporary.  This happens with my MIDI set up as well as my QWERTY computer keyboard.  Any suggestions?  Thank you.

**Comment by meszaros-lajos-gyorgy** [comment]
Sean made some improvements over the recent days, the reason might have been caused by the browser caching in older versions of some of the files, which are now probably invalidated by your browser. I'm going to close the ticket, but feel free to open a new one, if you encounter the issue again.
