### ISSUE TITLE
Scale Workshop not loading

### ISSUE THREAD

**Issue by Tonyyyyyyyyyyyyyyyyy** [SeanArchibald/scale-workshop#112]
Hi there,

Firstly, I'd like to say that the Scale Workshop is a really wonderful and impressive resource. I know very little about microtonal music (and computers), but I've really enjoyed playing around with different tunings, and am very grateful to the creator for sharing this. 

I've just noticed that, in the past couple of days, the Scale Workshop page has stopped loading. I've tried it on a couple of browsers, and the result is the same. Maybe it's my laptop (and, as I mentioned, I'm not good with computers), but I thought I'd just mention this in case a bug's cropped up that's useful for you to know about.

I've attached a screenshot of what happens when I load it on Google Chrome.

In any case, thank you very much for your service, and all the best to you.

<img width="1187" alt="Screen Shot 2020-12-05 at 2 10 24 PM" src="https://user-images.githubusercontent.com/75532425/101245284-a6ee5980-3703-11eb-9d0b-b4d920b243ef.png">

**Comment by SeanArchibald** [comment]
A new version was released this week - that might have caused the problem.

Please can you try clearing your browser cache and then refresh the Scale Workshop page? That should fix it, but if not then let me know.

**Comment by Tonyyyyyyyyyyyyyyyyy** [comment]
Clearing the browser cache has worked. Thanks a lot for your help!
