### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#113]
The app has unexpected/broken behaviour when using it soon after a new release, if the user has already accessed the app and the javascript has been locally cached in the browser.

The workaround is for the user to clear their browser cache. But it's a bad experience for users.

Proposed solution, I don't yet know how it would be implemented in javascript, but on including the scripts in the page, the URL should automatically have a parameter with the version number e.g. scaleworkshop.js?v=1.1

**Comment by meszaros-lajos-gyorgy** [comment]
I think at the moment you manually have to add that version to the html file. Since you are not using any backend you cannot automate that as you would do with PHP.

**Comment by meszaros-lajos-gyorgy** [comment]
Another solution is to not directly add the scripts via <script> tags, but by creating a small inline javascript code, which would do that for you: a bootloader. You store all the URLs for the script files as an array of string, then for every string you would create a new script element and add it to the <body>. That way you can add a version after the URLs.

```html
<script>
const files = ['src/js/model.js', 'src/js/constants.js', ...]
const version = '1.1'

files.forEach(src => {
  const script = document.createElement('script')
  script.src = src + '?' + version
  document.body.appendChild(script)
})
</script>
```

The only issue, that might arise is that you might need to wait for one script to be loaded before loading another, but I'm not 100% sure on this.

**Comment by SeanArchibald** [comment]
Cheers. I've done it by manually adding the version number as a cache busting parameter on each js file. This is just another thing I'll have to do each time we do a release
