### ISSUE TITLE
Tempo sync beating doesn't work after last update

### ISSUE THREAD

**Issue by MaxSamo** [SeanArchibald/scale-workshop#116]
![зображення](https://user-images.githubusercontent.com/62847898/102409316-82458c00-3ff7-11eb-9db3-fbd6c5787e15.png)
quotes are added to the second part of the ratio which creates an error

**Comment by SeanArchibald** [comment]
Thanks for reporting this. We'll need to fix this and roll out an update

**Comment by SeanArchibald** [comment]
A fix is currently in the develop branch, to be included in the next release, and in the meantime the fix can be tested here:
https://sevish.com/scaleworkshop-dev/
