### ISSUE TITLE
Summary: fixes + Base note bug

### ISSUE THREAD

**Issue by Da4mula** [SeanArchibald/scale-workshop#118]
My Omnisphere didn't play the right notes and Serum did't load the files.

After looking at the posts here I saw 2 solutions, each fixing one of my issues.

First open up the file with a text editor
Fix 1: Try deleting the 4th line which has a link to sevish.com
Fix 2: Delete the 'Functional Tuning' section. (delete all lines beginning from: '[Functional Tuning]', but leave the last line: '[Scale End]')
Than save the file as a .tun file and load it in your vst.

This fixed everything for me, except for that the base note (A4) plays a way higher note in Omnisphere and a way lower note in Serum. I read a post which said the base note got muted, maybe in his/her case the note got too low/high to hear, but that's just a speculation. There must be some logic behind this bug.

**Comment by SeanArchibald** [comment]
Hi, are both fixes necessary to get the tun files working? Or just either one of those fixes?

The development branch of the app has some changes to the tun exporter. Please can you try exporting a file from https://sevish.com/scaleworkshop-dev/ and let me know how it works in Omnisphere and Serum?

If possible I want to keep the URL because it allows a user to return to their original work, which might otherwise be lost if this URL was omitted from the exported file. Lines starting with ; are comments, and if these comment lines are affecting synths then I can only suggest that the synths are not following the tun spec correctly.

**Comment by Da4mula** [comment]
> Hi, are both fixes necessary to get the tun files working? Or just either one of those fixes?
> 
> The development branch of the app has some changes to the tun exporter. Please can you try exporting a file from https://sevish.com/scaleworkshop-dev/ and let me know how it works in Omnisphere and Serum?
> 
> If possible I want to keep the URL because it allows a user to return to their original work, which might otherwise be lost if this URL was omitted from the exported file. Lines starting with ; are comments, and if these comment lines are affecting synths then I can only suggest that the synths are not following the tun spec correctly.

Each fix solved one problem. deleting the link made Serum able to use the file, Deleting the Functional Tuning section made it work properly in Omnisphere.

I tried https://sevish.com/scaleworkshop-dev/ and that fixed the problem for Omnisphere. It even fixed the base note bug! But without removing the link Serum couldn't read it.

I have one tuning file that Serum could read with the link, so I compared them:

Working-file-link: ; https://sevish.com/scaleworkshop/?name=19%20equal%20divisions%20of%202%2F1&data=66%2F64%0A69%2F64%0A71%2F64%0A74%2F64%0A77%2F64%0A80%2F64%0A83%2F64%0A86%2F64%0A89%2F64%0A92%2F64%0A96%2F64%0A99%2F64%0A103%2F64%0A107%2F64%0A111%2F64%0A115%2F64%0A119%2F64%0A123%2F64%0A128%2F64&freq=277.3333333333333&midi=60&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ

Non-working-file-link: ; https://sevish.com/scaleworkshop-dev/?name=53%20equal%20divisions%20of%202%2F1&data=22.641509433962263%0A45.283018867924525%0A67.9245283018868%0A90.56603773584905%0A113.2075471698113%0A135.8490566037736%0A158.49056603773585%0A181.1320754716981%0A203.77358490566036%0A226.4150943396226%0A249.0566037735849%0A271.6981132075472%0A294.33962264150944%0A316.9811320754717%0A339.62264150943395%0A362.2641509433962%0A384.90566037735846%0A407.5471698113207%0A430.18867924528297%0A452.8301886792452%0A475.47169811320754%0A498.1132075471698%0A520.754716981132%0A543.3962264150944%0A566.0377358490566%0A588.6792452830189%0A611.3207547169811%0A633.9622641509434%0A656.6037735849056%0A679.2452830188679%0A701.8867924528302%0A724.5283018867924%0A747.1698113207547%0A769.8113207547169%0A792.4528301886792%0A815.0943396226414%0A837.7358490566037%0A860.3773584905659%0A883.0188679245282%0A905.6603773584905%0A928.3018867924528%0A950.9433962264151%0A973.5849056603773%0A996.2264150943396%0A1018.8679245283018%0A1041.509433962264%0A1064.1509433962262%0A1086.7924528301887%0A1109.433962264151%0A1132.0754716981132%0A1154.7169811320755%0A1177.3584905660377%0A1200.&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ

What I noticed is that the non-working-file-link is way longer. The length of the link makes it use another line and I think that might be the cause of the error. The non-working-file-link uses decimals while the working-file-link doesn't.

**Comment by SeanArchibald** [comment]
I think we already fixed this one. If exporting tun for Omnisphere use the v1 export option rather than v2.
