### ISSUE TITLE
Cannot find Non-Octave Equal-Temperament Scale Creation Ability

### ISSUE THREAD

**Issue by RicardoMadGello** [SeanArchibald/scale-workshop#119]
This is my pet project for a few decades, but slow at it.

50Hz & 60Hz have always fascinated me, so I figure making an Equal-Temperament Scale with those two would be fun to play in.

60/50^1/2 [SQRT(60/50)] would be the microtonal interval going up the scale
50/60^1/2 [SQRT(50/60)] going down the scale

I see only Octave-Based under Equal-Temperament.

Can you add a way to pick two frequencies (50Hz & 60Hz in my personal Octave 1), then calculate the interval between them (54.77226Hz), to create the 1D scale horizontally, then Octavate this 1D non-octave-based equal-temperament scale to 2D with PrevLowerOctave*2 vertically up & PrevUpperOctave/2 vertically down the page for the full map?

Any way to add this sort of non-octave equal-temperament that has been Octavated like so?

I choose 50Hz & 60Hz for obvious reasons, but other folks may need to use their own pair of Bass/Base Tone/Frequency/Note Pair.

Calculating out to 64-significant digit math precision would be great for my art project that spins-off from this as well, but 3-digits I guess everyone says is fine for music. 

Thanks!
--

![50Hz-54 77226Hz-60Hz Octaves -42-+42](https://user-images.githubusercontent.com/78683881/107144607-31fcf300-68f1-11eb-96f1-9e58bc606ac4.jpg)

**Comment by SeanArchibald** [comment]
It's already possible - see screenshot attached
  
  
   
  
  
   https://sevish.com/scaleworkshop/?name=2%20equal%20divisions%20of%2060%2F50&data=157.82064350027628%0A315.64128700055255&freq=50&midi=48&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ
  
  
   
  
  
   Have fun!
  
  
   
  
  
   S
  
  
   
  
  
   
    On 07/02/2021 10:59 RicardoMadGello <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   This is my pet project for a few decades, but slow at it.
   50Hz & 60Hz have always fascinated me, so I figure making an Equal-Temperament Scale with those two would be fun to play in.
   60/50^1/2 [SQRT(60/50)] would be the microtonal interval going up the scale50/60^1/2 [SQRT(50/60)] going down the scale
   I see only Octave-Based under Equal-Temperament.
   Can you add a way to pick two frequencies (50Hz & 60Hz in my personal Octave 1), then calculate the interval between them (54.77226Hz), to create the 1D scale horizontally, then Octavate this 1D non-octave-based equal-temperament scale to 2D with NextLowerNote*2 vertically up & NextUpperNote/2 vertically down the page for the full map?
   Anyway to add this sort of non-octave equal-temperament that has been Octavated like so?
   I choose 50Hz & 60Hz for obvious reasons, but other folks may need to use their own pair of Bass Note.
   Thanks!

**Comment by vsicurella** [comment]
For a little more context, here's how to do that yourself - open Equal Temperament, change "Interval to Divide" (2/1) into 60/50, choose 2 as Number of Divisions, and press OK.

Side note - 60 / 50 can be reduced to 6/5, which is a 5-limit just intonation minor third, so you can think your scale as a minor third split in half. Since every other note will be a fully-diminished chord (well, some sort of diminished at least!), it will kinda be like a octatonic whole/half step scale, except they're actually equal steps.

**Comment by RicardoMadGello** [comment]
Sweet!Thanks!be safeOn Feb 9, 2021 9:34 AM, Vincenzo Sicurella <notifications@github.com> wrote:
For a little more context, here's how to do that yourself - open Equal Temperament, change "Interval to Divide" (2/1) into 60/50, choose 2 as Number of Divisions, and press OK.
Side note - 60 / 50 can be reduced to 6/5, which is a 5-limit just intonation minor third, so you can think your scale as a minor third split in half. Since every other note will be a fully-diminished chord (well, some sort of diminished at least!), it will kinda be like a octatonic whole/half step scale, except they're actually equal steps.

**Comment by RicardoMadGello** [comment]
more study now.thanksOn Feb 9, 2021 9:34 AM, Vincenzo Sicurella <notifications@github.com> wrote:
For a little more context, here's how to do that yourself - open Equal Temperament, change "Interval to Divide" (2/1) into 60/50, choose 2 as Number of Divisions, and press OK.
Side note - 60 / 50 can be reduced to 6/5, which is a 5-limit just intonation minor third, so you can think your scale as a minor third split in half. Since every other note will be a fully-diminished chord (well, some sort of diminished at least!), it will kinda be like a octatonic whole/half step scale, except they're actually equal steps.
