### ISSUE TITLE
ET above 16TET doesn't work

### ISSUE THREAD

**Issue by Ross-Oliver** [SeanArchibald/scale-workshop#121]
For some reason (I don't know why), whenever I export a .tun file and import into Serum, it won't register a file above 16TET. I don't know why that is, and I'm sure that I'm importing it correctly but it still isn't happy about something. When I tried 19TET (for example), instead of saying 12TET... like it did before, it said (none).

**Comment by SeanArchibald** [comment]
Inside the .tun file you should see a line with a URL inside it. If so, please try deleting that line, saving the file, then try to load it into Serum. Does that work?
