### ISSUE TITLE
Sound issues (again) - might be my system?

### ISSUE THREAD

**Issue by Orangery-DS** [SeanArchibald/scale-workshop#122]
Hello Sean and the helpers.

I am having sound issues again.  I can play the qwerty keyboard for a short while, then the sound cuts out.  Okay once I refresh the screen but sound continues to drop out.  I imagine it's Microsnot Windows 10 updates that have screwed it up; any ideas?

Many thanks for sharing such a superb bit of kit (once I get the sound working properly).

**Comment by meszaros-lajos-gyorgy** [comment]
Hi!
What is the browser you are using?

**Comment by meszaros-lajos-gyorgy** [comment]
I can reproduce it setting Amplitude Envelope for percussive long or percussive medium and turning delay on. Interestingly when the sounds stop playing and I disable delay, then things seem to go back to normal for a few notes, then die off again.

**Comment by Orangery-DS** [comment]
Hi Ljos

I'm using an older version of Google Chrome but the sound issue was fine
for a weeks.

Thanks.

**Comment by SeanArchibald** [comment]
Going to close this one as we have issue #126 to track this bug. Thanks for your report!
