### ISSUE TITLE
Sound cuts out - oscillators/gain nodes not being reused

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [SeanArchibald/scale-workshop#126]
Found a nice debug tool for chrome to inspect web audio nodes: https://chrome.google.com/webstore/detail/web-audio-inspector/cmhomipkklckpomafalojobppmmidlgl

This tool shows that Scale Workshop is not re-using oscillator and gain nodes after playing a single note with it and since web audio doesn't do any garbage collection it can pile up and possibly cause all the audio stopping issues that have been reported here.

Please keep in mind, that on the screenshots these notes are pressed and released immediately, yet their nodes won't get cleaned up.

![1 note](https://user-images.githubusercontent.com/2386064/127786595-21db4b11-61ab-4e1b-94d3-d6bca88031c7.png)
![2 notes](https://user-images.githubusercontent.com/2386064/127786596-4805dd33-ca9a-404a-a1f7-59ecd4fa1b51.png)
![5 notes](https://user-images.githubusercontent.com/2386064/127786598-cf63dfb5-c914-420f-84c5-8400dce9c299.png)
![14 notes](https://user-images.githubusercontent.com/2386064/127786600-1254e8b7-6990-4938-b0d4-b3a1ea600014.png)

In the screenshots I'm using the percussive long setting: https://sevish.com/scaleworkshop/?name=12%20equal%20divisions%20of%202%2F1&data=100.%0A200.%0A300.%0A400.%0A500.%0A600.%0A700.%0A800.%0A900.%0A1000.%0A1100.%0A1200.&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=triangle&ampenv=organ

**Comment by meszaros-lajos-gyorgy** [comment]
One possible solution is to pre-create N oscillator and gain nodes, wire them up and keep an internal counter, that goes through all the nodes one after another as you press notes. The counter would loop over and start from the first node and skip all notes, which are currently being played. Similarly to synthesizers with fixed number of voices, there would be a limit on how many sounds you can press simultaniously and subsequent notes could either be ignored, or played by force-releasing pressed notes in various order.

**Comment by meszaros-lajos-gyorgy** [comment]
Delay also looks cool, as seen in this screenshot
![delay](https://user-images.githubusercontent.com/2386064/127786760-80ea83e3-97da-4731-b112-d310d5438e6e.PNG)

**Comment by SeanArchibald** [comment]
Ok! Think I have enough info to try fixing this. Good investigation!

**Comment by SeanArchibald** [comment]
Fix is now in the develop branch!

When the synth is initialised it will start a limited number of oscillators which are then reused. It's a round-robin style voice allocation which tries to avoid voice stealing. Max polyphony will be 6 by default (less taxing on low powered systems) but users can increase the max polyphony in a setting which will be automatically saved/recalled in browser localStorage.

It's been a long time coming...

**Comment by SeanArchibald** [comment]
Fixed in 1.4.1
