### ISSUE TITLE
unexpected result using rank-2 generator

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#129]
Using n-of-edo as a generator and selecting something non-default for Up/Down causes an unexpected result.
Reproducible on develop branch - https://sevish.com/scaleworkshop-dev
I'll update here as I do more testing.

![rank-2-issue](https://user-images.githubusercontent.com/11957541/132992063-046370b4-2b76-432c-9911-e046b1a34610.png)

**Comment by vsicurella** [comment]
Sorry, and thanks for catching this. My tests for "transposeSelf" are missing negative transpositions, which happen to not work for a few cases. I'll remedy this now!

**Comment by vsicurella** [comment]
I had forgotten to add proper negative handling to transposeSelf and moduloLine - but I'm about to submit a PR that fixes this.

**Comment by SeanArchibald** [comment]
working well for me. merged your PR :)
