### ISSUE TITLE
Add option to remap keyboard keys

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [SeanArchibald/scale-workshop#19]
Hi!

I know it's an edge case, but the Hungarian keyboard layout has the Y and Z keys flipped (we have QWERTZ instead of QWERTY), so it would be nice, if there would be a way to switch those 2 keys in the app somehow.

**Comment by SeanArchibald** [comment]
Supporting other keyboard layouts seems very important to me, so I have added an option under 'Note input settings' > 'Keyboard layout'

The Hungarian mapping here is a copy of the English mapping with Z and Y swapped. Lajos can you test for me to confirm that it's working? Easiest way is to clone/download the develop branch and open index.htm. Let me know if you find any other keys out of place

**Comment by meszaros-lajos-gyorgy** [comment]
Certainly, I'll check it and drop a feedback in a sec...

**Comment by meszaros-lajos-gyorgy** [comment]
The Z-Y flip works like a charm, though I found a few other keys, that are on the edge of the keyboard and need switching. I'll search them all and drop a message with every one of them included.

**Comment by meszaros-lajos-gyorgy** [comment]
Here is the final version with all the changes:

```javascript
  HU: {
    // keycode: [row, col]
    89: [-1,0], // y
    88: [-1,1], // x
    67: [-1,2], // c
    86: [-1,3], // v
    66: [-1,4], // b
    78: [-1,5], // n
    77: [-1,6], // m
    188: [-1,7], // ,
    190: [-1,8], // .
    189: [-1,9], // -
    65: [0,0], // a
    83: [0,1], // s
    68: [0,2], // d
    70: [0,3], // f
    71: [0,4], // g
    72: [0,5], // h
    74: [0,6], // j
    75: [0,7], // k
    76: [0,8], // l
    186: [0,9], // é
    222: [0,10], // á
    220: [0,11], // ű
    81: [1,0], // q
    87: [1,1], // w
    69: [1,2], // e
    82: [1,3], // r
    84: [1,4], // t
    90: [1,5], // z
    85: [1,6], // u
    73: [1,7], // i
    79: [1,8], // o
    80: [1,9], // p
    219: [1,10], // ő
    221: [1,11], // ú
    49: [2,0], // 1
    50: [2,1], // 2
    51: [2,2], // 3
    52: [2,3], // 4
    53: [2,4], // 5
    54: [2,5], // 6
    55: [2,6], // 7
    56: [2,7], // 8
    57: [2,8], // 9
    192: [2,9], // ö
    191: [2,10], // ü
    187: [2,11] // ó
  }
```

**Comment by SeanArchibald** [comment]
I've just updated develop with your changes to the keymap

**Comment by meszaros-lajos-gyorgy** [comment]
It works very well! I've also tested it on Mac, which - as expected - has some keyboard differences yet again, but I don't care at the moment. I'm happy to know, that the Z and Y keys are correctly flipped. You can mark this ticket done!

**Comment by SeanArchibald** [comment]
thanks for the help on this one!
