### ISSUE TITLE
Do not start AudioContext until user has interacted with page

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#20]
> The Web Audio autoplay policy will be re-enabled in Chrome 70 (October 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu

Scale Workshop will be affected by the above changes because it starts the AudioContext on load.

**Comment by SeanArchibald** [comment]
Thanks @meszaros-lajos-gyorgy !

**Comment by meszaros-lajos-gyorgy** [comment]
no problem!
