### ISSUE TITLE
Input type number funkyness in 'Generate equal temperament'

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [SeanArchibald/scale-workshop#21]
When I open the 'Generate equal temperament' window and click into the 'Number of divisions' field, then I see, that it's an input type number. If I click on the arrows on the right side of it or press the up/down buttons on my keyboard, I would expect it to increment or decrement by 1. Instead it first adds 0.0001 to the number, then it works correctly. I didn't test other number fields and I've only tested it in chrome 69 on windows 7.
![1](https://user-images.githubusercontent.com/2386064/46441738-b65e6a80-c767-11e8-9126-f964f2a4874e.JPG)
![2](https://user-images.githubusercontent.com/2386064/46441739-b65e6a80-c767-11e8-83f3-a98501d90f29.JPG)
![3](https://user-images.githubusercontent.com/2386064/46441740-b65e6a80-c767-11e8-98c7-7c1504200f23.JPG)

**Comment by SeanArchibald** [comment]
thanks, will look into it

**Comment by meszaros-lajos-gyorgy** [comment]
Setting `input_number_of_divisions`'s `min` attribute from `0.0001` to `1` solves the issue for that input field.

**Comment by SeanArchibald** [comment]
will be fixed in next ver
