### ISSUE TITLE
can there be a note added on the web GUI about this? 

### ISSUE THREAD

**Issue by bipwormz** [SeanArchibald/scale-workshop#22]
I told Sean Sevish "So, it works great, but when I turn on the Delay Effect, the QWERTY kbd
turns silent. Then I have to click "Keyboard Disabled" at the top right,
that turns the keyboard on, with the Delay Effect."

FYI, I entered the Workshop from Mr. Pepper's post here:
https://www.facebook.com/groups/xenwiki/permalink/2126926934239966/
=--=-
Sean replied: 
"What I think you're describing is by design. The qwerty keyboard is disabled whenever an input box, slider or checkbox is selected, to prevent notes from playing while entering data with the keyboard. Once the focus is on a non-input element, the keyboard will work again. Slightly annoying if you're trying to switch on the delay though I don't see a way around this at the mo."
=--=-=
**What I'm suggesting is a note about that next to the delay switch**, so noobs don't think they broke something, or that something is broken. I intuitively clicked other places until it fixed, but I'm not sure noobs would.

**Comment by SeanArchibald** [comment]
I intend to add more notes and info on the page. As this project gets bigger and bigger I can really see the need for it. See issue #18

Need to think of an elegant solution. Soon there will be a lot more than 1 checkbox and I don't feel good about adding the same note next to every checkbox.

When the project is more feature complete I will consider a UI overhaul to address these kinds of issues that confuse new users

**Comment by bipwormz** [comment]
cool.

**Comment by bipwormz** [comment]
I think making it very noob friendly is a good goal to keep in mind. It could be a great resource for people who don't even know what xen is to experiment with it. 

I could see this getting linked places like BoingBoing and LiveSquid,...i.e. popular curated "hey look at this nifty thing!" tech blogs. 

And also at the same time being useful for xen musicians, especially ones who have trouble using Scala.  There seem to be some of those.

**Comment by SeanArchibald** [comment]
going to close this issue as the next release will have more beginner friendly tooltips baked in. will continue to improve this over time.

I didn't add a note about disabling the qwerty keyboard, as it would apply to all input elements so not specific to the delay on/off switch
