### ISSUE TITLE
Feature request - Modes via negative generators

### ISSUE THREAD

**Issue by jimbla** [SeanArchibald/scale-workshop#26]
Sometimes you don't remember the mode pattern. In those instances it would be cool to be able to specify that you want a scale that goes 7 positive generators up and 5 generators down. In Scala this is accomplished in the File/Linear Temperament dialog as two number boxes. When you add negative generators to the first box, the positive generators goes down in the second box. This is very useful, because many times you want the symmetric mode which has an equal number of positive and negative generators, and having two updating number boxes makes the symmetry apparent to you.

**Comment by SeanArchibald** [comment]
This has been requested once before. Would be useful indeed

**Comment by jimbla** [comment]
Any progress on this? I could really use it. The only thing I fire up Scala for these days is to rotate a scale and I think it’s so silly, ha ha. Scala doesn’t remember your settings either, so if you want to generate all the rotations of a scale you have to edit the dialogue that many times.

**Comment by SeanArchibald** [comment]
Thanks for coming back on this one. I will try to make progress on this soon. It would be a really good addition.

**Comment by SeanArchibald** [comment]
You can download the develop branch as a zip file here: https://github.com/SeanArchibald/scale-workshop/archive/develop.zip

Extract the contents to some directory and then run the index.htm file inside. This should allow you to test the development version of Scale Workshop on your local machine. Note that some functions of the app work differently when running from your local machine, but this should allow you to test the generators up/down function.

I'm keen to find out if this implementation always produces accurate results (so far in my testing it has been ok).

I would also like to improve the language/labels used for this feature but not sure the best words to use.

**Comment by SeanArchibald** [comment]
Actually I have an easier way for you to test. Just use this alternative link: http://sevish.com/scaleworkshop-dev/

**Comment by SeanArchibald** [comment]
Added in 0.9.2
