### ISSUE TITLE
Built-in webaudio synth

### ISSUE THREAD

**Issue by suhr** [SeanArchibald/scale-workshop#3]
Since Github issues are not only about bugs but also about feature requests (see label “enhancement”), I'll put it here.

([Web audio resources](https://github.com/alemangui/web-audio-resources))

Tone.js is popular, but it is too much 12EDO-centric. While [wad](https://github.com/rserota/wad) looks interesting.

**Comment by suhr** [comment]
Idea: graduated (like a ruler) [theremin](https://femurdesign.com/theremin/).

**Comment by SeanArchibald** [comment]
I agree that a webaudio synth would make this project feel more complete.

My ideas so far:
* can accept MIDI input form other devices
* display a fretboard-like grid on the screen for touch devices
* use QWERTY keyboard to play the same grid as above

Those are just some ideas. I have a lot of other work to do on this project before I add a synth in :)

**Comment by SeanArchibald** [comment]
Just FYI I started a 'synth' branch but haven't pushed any commits up to github yet.. Just trying to find the time to start this new effort. Expect to see more progress here in the future.

**Comment by SeanArchibald** [comment]
Scale Workshop now acts as a very basic polyphonic synth, triggered by pressing buttons on your computer keyboard (qwerty). There's a lot more work to be done, but you can find early progress on the synth branch: https://github.com/SeanArchibald/scale-workshop/tree/synth

Feedback, suggestions and issue reports are welcome at this point.

**Comment by SeanArchibald** [comment]
The synth branch has been merged into master for the 0.8 release. If you want to test the synth please just checkout the master branch. I might close this issue soon but more specific issues can be added to the tracker at any time
