### ISSUE TITLE
If there's no scale name/description given, there should be placeholder text for programs expecting a description line

### ISSUE THREAD

**Issue by JLMoriart** [SeanArchibald/scale-workshop#41]
I had an issue importing a scala file (here: http://www.microtonalsoftware.com/scl-scala-to-mts-converter.html) which was fixed when I gave the tuning a description. I assume placeholder "no-description" text in the case of no scale name would do the trick.

**Comment by SeanArchibald** [comment]
To do: When user doesn't enter a tuning name, exporting .scl should always contain a placeholder name

**Comment by SeanArchibald** [comment]
Develop branch now has the fix. Here is the link in case you want to test this yourself: sevish.com/scaleworkshop-dev/

The fix will go into the next stable version soon. Going to close this issue for now.
