### ISSUE TITLE
cannot enter 'n\m' interval

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#47]
seeing issues when entering an interval with the format `n\m`, this looks like a regression from recent refactoring

<img width="313" alt="Screenshot 2019-03-13 at 22 24 40" src="https://user-images.githubusercontent.com/11957541/54318690-f3643e00-45de-11e9-8a4e-e9a9ce802654.png">

<img width="123" alt="Screenshot 2019-03-13 at 22 26 14" src="https://user-images.githubusercontent.com/11957541/54318719-17278400-45df-11e9-8b66-9c1785bfe69a.png">

**Comment by meszaros-lajos-gyorgy** [comment]
https://github.com/SeanArchibald/scale-workshop/blob/develop/js/helpers.js#L49
Just change the '/' in split to '\\' and it should fix the issue.

**Comment by SeanArchibald** [comment]
thanks! that was an easy fix
