### ISSUE TITLE
Notes keep playing

### ISSUE THREAD

**Issue by henioe** [SeanArchibald/scale-workshop#53]
When I press a key on my Keyboard the note in Scale-workshop won't stop playing even if I let go. Only the Quiet button can stop it.
I connected my normal Keybord with an USB-Midi-Cable (the rectangle one) to my Apple MacBook. Am I missing something?

**Comment by meszaros-lajos-gyorgy** [comment]
#55 fixes this for both Firefox and Safari.

**Comment by SeanArchibald** [comment]
This should now be fixed in the develop branch. Could you check here and let me know if it's working now? http://sevish.com/scaleworkshop-dev/

**Comment by henioe** [comment]
Yes it is. Nice work! It’s a really good tool… and toy ;)

**Comment by SeanArchibald** [comment]
Thanks for checking that! Going to close this ticket for now. The fix will be merged into master branch soon
