### ISSUE TITLE
Pad notes getting stuck when released too early

### ISSUE THREAD

**Issue by BeesNation** [SeanArchibald/scale-workshop#54]
On the "Pad" amplitude envelope setting, when a note is played and then released before the maximum amplitude is reached the sound stops but the note appears stuck down and cannot be played again until the browser is refreshed.
On Firefox with qwerty keyboard.

**Comment by meszaros-lajos-gyorgy** [comment]
The following error can be seen when the error happens:

![Képernyőfotó 2019-04-15 - 9 32 29](https://user-images.githubusercontent.com/2386064/56114589-9eab3e80-5f61-11e9-8c4b-5467be1df90e.png)

It points to this line: https://github.com/SeanArchibald/scale-workshop/blob/develop/js/synth/Voice.js#L70

**Comment by meszaros-lajos-gyorgy** [comment]
Found the culprit! When the ramp up of the pad gets interrupted, then the volume gets held with `cancelAndHoldAtTime()` and then an exponential ramp will occur all the way to 0.001. In Firefox (and Safari) there is no `cancelAndHoldAtTime()`, but it is substituted with `cancelScheduledValues()`, which will immediately reset the volume back to the value before the ramp begun, which was 0. Then `exponentialRamToValueAtTime()` will be called with values going from 0 to 0.001, where 0 is invalid.

**Comment by SeanArchibald** [comment]
Thanks @meszaros-lajos-gyorgy !

@BeesNation are you still seeing the issue if you try here? http://sevish.com/scaleworkshop-dev/

**Comment by SeanArchibald** [comment]
Going to close this one as I have tested 1.0.0 vs 1.0.1 in Firefox & Safari and no longer seeing the issue in 1.0.1
