### ISSUE TITLE
Sound on by default

### ISSUE THREAD

**Issue by jimbla** [SeanArchibald/scale-workshop#57]
I use my MIDI keyboard simultaneously with Scale Workshop all the time, and every time I find that the sound coming out of Scale Workshop is on by default and is triggered together with my MIDI keyboard. To stop it, I have to go into the browser, find the Scale Workshop tab and press on all kinds of things to get to a slider so that I can manually turn down the volume. It would be nice if sound was off by deafult or if the QUIET button also acted as a mute button.

**Comment by SeanArchibald** [comment]
The fix for issue #56 will also resolve this

**Comment by SeanArchibald** [comment]
PR #59 should improve this issue. I'm currently testing Lajos' recent changes which are checked out here: https://sevish.com/scaleworkshop-dev/

@jimbla does this stop Scale Workshop making the unwanted sounds? Any other feedback welcome!

**Comment by SeanArchibald** [comment]
this fix has been merged into master branch now
