### ISSUE TITLE
keyboard works from website but not from github download

### ISSUE THREAD

**Issue by billystiltner** [SeanArchibald/scale-workshop#61]
the music keyboard works from android when online from sevish.com but after downloading and unzipping from home offline there is no keyboard option in the dropdown menu

**Comment by meszaros-lajos-gyorgy** [comment]
Hi!

As far as I know, the touch keyboard only works on mobile devices. It's not implemented in a way to work on desktop browsers. (It might worth revisiting the implementation to make it work on desktop too)

**Comment by meszaros-lajos-gyorgy** [comment]
This will be shipped in the upcoming version of Scale workshop.
