### ISSUE TITLE
MIDI controller input

### ISSUE THREAD

**Issue by SeanArchibald** [SeanArchibald/scale-workshop#7]
Allow a MIDI controller to be used as input for the synth

**Comment by SeanArchibald** [comment]
Web MIDI API is currently only supported by Chrome and Opera
https://caniuse.com/#feat=midi

Nice info should be shown to users of non-supported browsers

**Comment by meszaros-lajos-gyorgy** [comment]
I'm more than happy to help you with this, if you need any, since I did a good amount of research on WebMIDI recently.

**Comment by SeanArchibald** [comment]
I saw your pull request, thank you! Can't wait to try it out on the weekend.

**Comment by SeanArchibald** [comment]
thanks!! this will go in the next version. will close this issue for now
