### ISSUE TITLE
Issue with the guide

### ISSUE THREAD

**Issue by An-Annoying-Cat** [SeanArchibald/scale-workshop#70]
There is no explanation for what rank-2 temperaments are and the program would benefit from having that.

**Comment by SeanArchibald** [comment]
I'm not convinced that explaining rank-2 temperaments is within the scope of the guide. The guide is to explain the functions of the software and tips for use - it assumes the user has some basic knowledge. If the user doesn't, there are education resources online that do a good job. Type "rank-2 temperament" into Google and first result is a wikipedia article.

If we were to assume no prior knowledge from the user then it would be necessary to include explanations of everything else in the app such as: cents, Hz, equal temperaments, harmonics, subharmonics, ratios, MIDI note numbers, moment of symmetry, degrees and so on.

**Comment by SeanArchibald** [comment]
Will close this issue now but will take it as feedback. Thanks!
