### ISSUE TITLE
Error in Functionnal Tuning section of exported TUN file

### ISSUE THREAD

**Issue by Lyoks38** [SeanArchibald/scale-workshop#82]
I've created a basic 5 tones scale using cents and exported it in .tun, and spotted an error in the Functionnal Tuning section of the exported file: 
![Screenshot 2020-01-17 at 12 03 02](https://user-images.githubusercontent.com/22156485/72607779-91bce080-3921-11ea-8186-6b2ebdd948d2.png)
The last note tuning should be note 5="#>-5 % 1200.000000 ~999" :)
I reproduce the issue everytime I use cents to describe my scale.

**Comment by meszaros-lajos-gyorgy** [comment]
@SeanArchibald a fix is available on the `develop` branch, can you deploy that for testing the fix?

**Comment by meszaros-lajos-gyorgy** [comment]
@Lyoks38 the fix have been published to the dev url: https://sevish.com/scaleworkshop-dev/ It worked correctly for me there, but could you please test it too? Thanks!

**Comment by zardini123** [comment]
I kept banging my head trying to figure out why importing the .tun files from the workshop into my synths was resulting in craziness.  I thought it was my synths acting up.  After a bunch of research I found it was the workshop adding that * instead of a %.  Please publish the fix to the main website when possible :)

**Comment by meszaros-lajos-gyorgy** [comment]
No feedback from @Lyoks38 for over a month now, assuming the fix works correctly.

**Comment by meszaros-lajos-gyorgy** [comment]
@zardini123 `1.0.4` is released, which contains this fix!

**Comment by zardini123** [comment]
Yay thank you @meszaros-lajos-gyorgy !
