### ISSUE TITLE
Minilogue Scale: Support Minilogue scale files

### ISSUE THREAD

**Issue by vsicurella** [SeanArchibald/scale-workshop#96]
The Korg Minilogue Librarian software allows you to dump tunings into a Minilogue. Sadly, Korg didn't properly implement KBM files, and it's impossible to map them correctly using a proper KBM file. They just ignore the root note and start the mapping on MIDI Note 0. It seems you can sort of working around this by changing the reference note & freq in the KBM file, but it's not really reliable.

They do support a proprietary format with the extension ".mnlgtuns" and it would be awesome to be able export in this format (and perhaps import) and the tuning mapped properly. 

To be more precise, there are two types - "mnlgtuns" and "mnlgtuno". The latter only holds data for 12 notes and assumes an octave period. Sadly, each note only has a range of [-50, +49] cents, with 1 cent resolution.

This will require some reverse engineering of the file type, but I don't think it will be too hard. The way they handle Scala files, based on how they look after exporting them from the synth to the computer, is like a bastardized Anamark Tuning file, so I suspect the ".mnlgtuns" file format to be similar.

There are some attached files here in case anyone wants to dig in before I get to it. All of these were saved by simply importing a Scala file (with no KBM) and re-saving it in the Minilogue format.

[Minilogue_Scale_Files.zip](https://github.com/SeanArchibald/scale-workshop/files/4327554/Minilogue_Scale_Files.zip)

**Comment by SeanArchibald** [comment]
Thanks @vsicurella ! I assume this one is now good to close
